-- ============================================================================
-- China Deep Travel — MySQL schema (MySQL 8.0+ / InnoDB / utf8mb4)
-- ----------------------------------------------------------------------------
-- Run with:  mysql -u <user> -p <db> < db/schema.mysql.sql
-- Or:        mysql -u <user> -p <db> -e "SOURCE db/schema.mysql.sql"
--
-- All primary keys are CHAR(36) UUIDs generated by the application
-- (crypto.randomUUID()). point_transactions / user_unlocked_articles /
-- email_verifications / password_resets / site_settings use AUTO_INCREMENT
-- BIGINT ids because they are never referenced by external rows.
--
-- Business-rule guarantees enforced here:
--   * users.current_points is the live balance; it is ONLY mutated inside a
--     transaction together with a point_transactions ledger row (see points.ts).
--   * user_unlocked_articles has a UNIQUE(user_id, article_id) key -> an already
--     unlocked article can never be charged twice (INSERT IGNORE is a no-op).
--   * point_transactions is append-only (no UPDATE/DELETE in app code) -> audit.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS point_transactions;
DROP TABLE IF EXISTS user_unlocked_articles;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS email_verifications;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS advertisements;
DROP TABLE IF EXISTS ad_slots;
DROP TABLE IF EXISTS point_packages;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS site_settings;

-- ----------------------------------------------------------------------------
-- Users (overseas email+password / Google OAuth)
-- ----------------------------------------------------------------------------
CREATE TABLE users (
  id              CHAR(36)     NOT NULL,
  name            VARCHAR(120) NOT NULL,
  email           VARCHAR(255) NOT NULL,
  password_hash   VARCHAR(255) NULL COMMENT 'NULL for OAuth-only accounts',
  role            ENUM('user','admin') NOT NULL DEFAULT 'user',
  current_points  INT          NOT NULL DEFAULT 0,
  email_verified  TINYINT(1)   NOT NULL DEFAULT 0,
  is_suspended    TINYINT(1)   NOT NULL DEFAULT 0,
  avatar_url      VARCHAR(512) NULL,
  locale          VARCHAR(10)  NOT NULL DEFAULT 'en',
  google_id       VARCHAR(120) NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_email (email),
  KEY idx_users_google (google_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Point packages (public top-up tiers; 1 USD = 30 CPT points)
-- ----------------------------------------------------------------------------
CREATE TABLE point_packages (
  id            CHAR(36)   NOT NULL,
  name          VARCHAR(120) NOT NULL,
  price_usd     DECIMAL(10,2) NOT NULL,
  points_amount INT         NOT NULL,
  bonus_points  INT         NOT NULL DEFAULT 0,
  badge         VARCHAR(80)  NULL,
  sort_order    INT         NOT NULL DEFAULT 0,
  is_active     TINYINT(1)  NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_packages_active (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Orders (top-up purchases; status driven by payment webhook / mock recharge)
-- ----------------------------------------------------------------------------
CREATE TABLE orders (
  id                       CHAR(36) NOT NULL,
  order_number             VARCHAR(64) NOT NULL,
  user_id                  CHAR(36) NOT NULL,
  package_id               CHAR(36) NULL,
  amount_usd               DECIMAL(10,2) NOT NULL,
  points_awarded           INT      NOT NULL,
  status                   ENUM('pending','completed','failed','refunded') NOT NULL DEFAULT 'pending',
  provider                 VARCHAR(32) NOT NULL DEFAULT 'stripe',
  stripe_payment_intent_id VARCHAR(255) NULL,
  paid_at                  DATETIME NULL,
  refunded_at              DATETIME NULL,
  created_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_orders_number (order_number),
  KEY idx_orders_user (user_id),
  KEY idx_orders_status_paid (status, paid_at),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_orders_pkg  FOREIGN KEY (package_id) REFERENCES point_packages (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Categories
-- ----------------------------------------------------------------------------
CREATE TABLE categories (
  id         CHAR(36) NOT NULL,
  name       VARCHAR(120) NOT NULL,
  slug       VARCHAR(120) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active  TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uk_categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Articles (premium guides). content is ONLY served by the API when the
-- caller has unlocked the article (server-side paywall — see getArticleBySlug).
-- ----------------------------------------------------------------------------
CREATE TABLE articles (
  id              CHAR(36)   NOT NULL,
  title           VARCHAR(255) NOT NULL,
  slug            VARCHAR(200) NOT NULL,
  excerpt         TEXT        NULL,
  content         LONGTEXT    NULL,
  cover_image_url VARCHAR(512) NULL,
  category_id     CHAR(36)    NULL,
  author_id       CHAR(36)    NULL,
  point_cost      INT         NOT NULL DEFAULT 15,
  is_free         TINYINT(1)  NOT NULL DEFAULT 0,
  is_featured     TINYINT(1)  NOT NULL DEFAULT 0,
  status          ENUM('draft','pending_review','published','archived') NOT NULL DEFAULT 'draft',
  tags            JSON        NULL,
  read_time_minutes INT       NULL,
  view_count      INT         NOT NULL DEFAULT 0,
  unlock_count    INT         NOT NULL DEFAULT 0,
  meta_title      VARCHAR(255) NULL,
  meta_description TEXT        NULL,
  published_at    DATETIME    NULL,
  created_at      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_articles_slug (slug),
  KEY idx_articles_cat (category_id),
  KEY idx_articles_status (status, published_at),
  KEY idx_articles_featured (is_featured),
  CONSTRAINT fk_articles_cat    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
  CONSTRAINT fk_articles_author FOREIGN KEY (author_id)  REFERENCES users (id)     ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- User unlocked articles (idempotent). The unique key is what makes a second
-- unlock attempt free.
-- ----------------------------------------------------------------------------
CREATE TABLE user_unlocked_articles (
  id           BIGINT      NOT NULL AUTO_INCREMENT,
  user_id      CHAR(36)   NOT NULL,
  article_id   CHAR(36)   NOT NULL,
  points_spent INT        NOT NULL DEFAULT 0,
  unlocked_at  DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_article (user_id, article_id),
  KEY idx_ua_user (user_id),
  KEY idx_ua_article (article_id),
  CONSTRAINT fk_ua_user    FOREIGN KEY (user_id)  REFERENCES users (id)    ON DELETE CASCADE,
  CONSTRAINT fk_ua_article FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Comments (article discussion). Nested replies via parent_id (one level).
-- status 'hidden' lets admins moderate without deleting the row.
-- ----------------------------------------------------------------------------
CREATE TABLE comments (
  id           CHAR(36)     NOT NULL,
  article_id   CHAR(36)     NOT NULL,
  user_id      CHAR(36)     NOT NULL,
  parent_id    CHAR(36)     NULL,
  content      TEXT         NOT NULL,
  status       ENUM('published','hidden') NOT NULL DEFAULT 'published',
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_comments_article (article_id, created_at),
  KEY idx_comments_parent (parent_id),
  CONSTRAINT fk_comments_article FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_user    FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE,
  CONSTRAINT fk_comments_parent  FOREIGN KEY (parent_id)  REFERENCES comments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Point transactions — immutable ledger. App code never UPDATEs/DELETEs rows.
-- ----------------------------------------------------------------------------
CREATE TABLE point_transactions (
  id            BIGINT   NOT NULL AUTO_INCREMENT,
  user_id       CHAR(36) NOT NULL,
  type          ENUM('purchase','unlock','refund','admin_adjustment','signup_bonus') NOT NULL,
  points_delta  INT      NOT NULL COMMENT 'positive = credit, negative = debit',
  balance_after INT      NOT NULL,
  reference_type VARCHAR(32) NULL,
  reference_id   CHAR(36)   NULL,
  admin_note     VARCHAR(255) NULL,
  created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pt_user_created (user_id, created_at),
  KEY idx_pt_ref (reference_type, reference_id),
  CONSTRAINT fk_pt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Email verification tokens
-- ----------------------------------------------------------------------------
CREATE TABLE email_verifications (
  id         BIGINT   NOT NULL AUTO_INCREMENT,
  user_id    CHAR(36) NOT NULL,
  token      VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  used       TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ev_token (token),
  CONSTRAINT fk_ev_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Password reset tokens
-- ----------------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
  id         BIGINT   NOT NULL AUTO_INCREMENT,
  user_id    CHAR(36) NOT NULL,
  token      VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  used       TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_prt_token (token),
  CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Ad slots (AD-01 .. AD-06) and advertisements
-- ----------------------------------------------------------------------------
CREATE TABLE ad_slots (
  id              CHAR(36) NOT NULL,
  slot_code       VARCHAR(16) NOT NULL,
  slot_name       VARCHAR(120) NOT NULL,
  width           INT      NULL,
  height          INT      NULL,
  is_mobile_hidden TINYINT(1) NOT NULL DEFAULT 0,
  position        INT      NOT NULL DEFAULT 0,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ad_slots_code (slot_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE advertisements (
  id            CHAR(36)   NOT NULL,
  slot_id       CHAR(36)   NOT NULL,
  title         VARCHAR(160) NOT NULL,
  image_url     VARCHAR(512) NULL,
  target_url      VARCHAR(512) NULL,
  advertiser    VARCHAR(120) NULL,
  is_active     TINYINT(1)  NOT NULL DEFAULT 1,
  start_date    DATE        NULL,
  end_date      DATE        NULL,
  priority      INT         NOT NULL DEFAULT 0,
  impression_count INT      NOT NULL DEFAULT 0,
  click_count   INT         NOT NULL DEFAULT 0,
  created_at    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ads_slot (slot_id),
  CONSTRAINT fk_ads_slot FOREIGN KEY (slot_id) REFERENCES ad_slots (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------------
-- Site settings (key/value)
-- ----------------------------------------------------------------------------
CREATE TABLE site_settings (
  id          BIGINT      NOT NULL AUTO_INCREMENT,
  `key`       VARCHAR(64) NOT NULL,
  value       TEXT        NULL,
  description VARCHAR(255) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_settings_key (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
-- Minimal seed (so the site boots and the mock recharge has packages to buy)
-- ============================================================================
INSERT INTO site_settings (`key`, value, description) VALUES
  ('welcome_bonus_points', '20', 'Points granted to a new user on signup'),
  ('points_per_usd', '30', 'Conversion rate: 1 USD = N CPT points');

INSERT INTO point_packages (id, name, price_usd, points_amount, bonus_points, badge, sort_order) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Starter',      5.00,  150,   0,   NULL,       1),
  ('22222222-2222-2222-2222-222222222222', 'Explorer',     15.00, 450,   60,  'Popular',   2),
  ('33333333-3333-3333-3333-333333333333', 'Adventurer',   30.00, 900,   180, 'Best Value',3),
  ('44444444-4444-4444-4444-444444444444', 'Nomad',        60.00, 1800,  480, NULL,       4);

INSERT INTO ad_slots (id, slot_code, slot_name, width, height, is_mobile_hidden, position) VALUES
  ('aaaa0001-aaaa-aaaa-aaaa-000000000001', 'AD-01', 'Homepage Hero Banner',            970, 250, 0, 1),
  ('aaaa0002-aaaa-aaaa-aaaa-000000000002', 'AD-02', 'Guides Sidebar (Desktop)',       300, 600, 1, 2),
  ('aaaa0003-aaaa-aaaa-aaaa-000000000003', 'AD-03', 'Article Inline',                 728, 90,  0, 3),
  ('aaaa0004-aaaa-aaaa-aaaa-000000000004', 'AD-04', 'Article Footer',                728, 90,  0, 4),
  ('aaaa0005-aaaa-aaaa-aaaa-000000000005', 'AD-05', 'Guide List Sidebar (Desktop)',  300, 250, 1, 5),
  ('aaaa0006-aaaa-aaaa-aaaa-000000000006', 'AD-06', 'Footer Banner',                 970, 90,  0, 6);

-- Seed admin account (email: admin@chinadeeptravel.com / password: Admin#2024)
INSERT INTO users (id, name, email, password_hash, role, current_points, email_verified, locale)
VALUES ('00000000-0000-0000-0000-000000000001', 'Site Admin', 'admin@chinadeeptravel.com',
        '$2a$12$ph66d7dMPb3V1XyBrt3/muGu9KENiWwlym6Ve/02ePn2a5z6iXkPK', 'admin', 0, 1, 'en');
